version: "3.6"

services:
  sifir-cyphernode-ui:
    image: sifir/cn-app-ui:0.0.1-local
    ports:
    # Port for NGINX to serve the UI on, change this if you have conflictsorts:
      - 3011:80
  sifir-cyphernode-app:
    image: sifir/cn-app:0.0.1-local
    command: npm start
    ports:
      - 3009:3009
      - 3010
    environment:
      # ---- NO NEED TO EDIT ENV VARIABLES HERE, use .env file instead #
      - CYPHERNODE_API_KEY=${CYPHERNODE_API_KEY}
      - CYPHERNODE_API_KEY_ID=${CYPHERNODE_API_KEY_ID}
      - CYPHERNODE_ONION_URL=${CYPHERNODE_ONION_URL}
      - CYPHERNODE_GATEKEEPER_CERT_CA=${CYPHERNODE_GATEKEEPER_CERT_CA}
      - CYPHER_GATEWAY_URL=https://gatekeeper:2009/v0/
      - SIFIR_APP_API_PORT=3009
      - SIFIR_APP_TOR_BRIDGE_PORT=3010
      # Endpoint used when pairing using Sifir sync service only
      - SIFIR_PAIRING_SERVER=https://keys.sifir.io
      - SIFIR_SYNAPSE_HOMESERVER=matrix.sifir.io
      - SIFIR_SYNAPSE_HOMESERVER_URL=https://matrix.sifir.io
      - SIFIR_SQLLITE_FILE=/data/sqlite/db.dat
      # - SIFIR_API_PAIRING_SECRET= # Generated at run time, or can be set statically here
      - SIFIR_API_PAIRING_KEY_EXPIRY=60000*5 # 5 mins expirty on pairing token
      - BRIDGE_COMMAND_BROADCAST_TIMEOUT=9000
      - DEBUG=sifir*
    volumes:
      - ./sifir-cn-app/data/:/data
    labels:
      - "traefik.docker.network=cyphernodeappsnet" 
      - "traefik.frontend.rule=PathPrefixStrip: /sifir" 
      - "traefik.frontend.passHostHeader=true" 
      - "traefik.enable=true"
      - "traefik.port=3010"
      - "traefik.frontend.entryPoints=http"
    networks: 
      - cyphernodeappsnet
networks:
   cyphernodeappsnet:
     external: true
